# Site settings
title: David Mwangi Mathenge
description: David Mwangi Mathenge
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: David Mwangi Mathenge
user_description: Software Engineer, Data Analyst, Python Enthusiast.
user_title: Software Developer
email: david.mathenge98@gmail.com
twitter_username: david_mwas
github_username:  DavidMwangi
gplus_username:  +davidmathengegoogleplus

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
